### ISSUE TITLE
todo/roadmap

### ISSUE THREAD

**Issue by benoitc** [helium/erlang-libp2p#71]
I'm wondering if you have a list of todo thing and things that are expected to work right now? I would like to try to use it in semi production with just the tcp protocol support for now. Let me know :)

**Comment by madninja** [comment]
@benoitc, we'll work on getting the README updated a bit with useful information. 

The main thing we're working on that will affect the API is the gossip group set up which isn't quite right yet. 

But if you're just using it for connecting and communicating with services it's been working pretty well for us in testing so far.

**Comment by benoitc** [comment]
ok i think the gossip group will be useful too, but will first test the peers connections to see if it does the trick :-)

**Comment by benoitc** [comment]
I'm back on that topic, I am interested by using libp2p in my project ad would like possibly to help the development if it goes in same direction. I am actually wondering of the following:

* how much the current code is interoperable right now.  did you try https://github.com/libp2p/interop. If not can you point where it diverges from the spec and if you would be interested by beeing compliant

* related to #91, can we add more transports right now? 
* is this possible also to make the gossiping layer exchangeable ? 

Please let me know, we can also discuss via mail or  irc about it.

**Comment by benoitc** [comment]
cc @madninja

**Comment by benoitc** [comment]
bump

**Comment by benoitc** [comment]
to be clear, my main goal is to have a fully compliant libp2p lib in erlang (at least at the same level as the rust one). So I would be interrested in knowing where you know it's actually differing and if that goal is OK for you.

**Comment by madninja** [comment]
@benoitc The libp2p "canonical" implementation seems to differ quite widely between the JS, Rust and Go implementations to the point that they are not believed to be interoperable. 

While I'd love to be interoperable it's currently not clear with which one we'd try to be compatible. The main inconsistencies we have right now are the underlying multiplexer protocol used. We use yamux but the other implementations changed that mid-stream. The other implementations do not protect against flooding attacks and other DDOS windowing/session attacks. 

We also have a fixed framing that we use for most of our streams that make our current streams incompatible with the libp2p ones. 

This got to the point where we are considering renaming the erlang-libp2p to something else. We would still use the multiprotocol, multiaddr,  and related p2p encoding modules but improved framing and security features. 

Let us know what your impressions are?

**Comment by benoitc** [comment]
@madninja sorry for the delayed response.

For me  the main reason I were interested in the libp2p protocol as "briefly" described on https://libp2p.io was the availability of library on different platform/languages . I would have expected that they all pass the [interoperability tests](https://github.com/libp2p/interop). I didn't test it myself , but if the libs are also each implementing differently parts of the specs, then it's losing its attractiveness (do you have a list of the difference in term of protocol btw?)  The other part is the ecosystem that seems to create itself around with side projects like [Peergos](https://github.com/Peergos/Peergos) .

I'm not against a different implementation, but then I think one of the key point would be documenting the protocol and co to create some kind of ecosystem (or community) around it. It would be harder to create such ecosystem than simply joining the libp2p project with another implementation imo.  It would require a lot more resources. Maybe it would be easier to make sure that all other libs are able to discuss each other like the ZMQ project is doing? 

Also how do you see the mobile support?

**Comment by benoitc** [comment]
bump :)

**Comment by madninja** [comment]
@benoitc The main difference is the "session" muxing protocols that each implementation supports. The main implementations, Rust, JS and Go seem to be (or maybe already have) converging on one that isn't yamux so we can look at implementing that as a protocol for the erlang implementation too. 

That would get us session compatibility. The various streams (services) that are built on top of this are currently very basic across the various implementations. We use a fixed header framing on all our stream implementations which many other service implementations don't. 

We also have some services that we think are more complete than the other implementations, like cryptographic challenge/response identification of a peer before allowing peer discovery. Ideally we would convince the other projects that our approach for some of these higher level services is a good thing and  that they should implement it too. We just haven't had the time since we're trying to ship product in short order. 

I think we can aim for compatibility at the session level at least and then work upwards on specific streams as they arise

**Comment by madninja** [comment]
@benoitc Those interop tests are (1) really old and (2) mostly undefined afaict?

**Comment by benoitc** [comment]
@madninja true for the interop test. I decided to give a shoot to libp2p, not sure where to start at the moment though :)

**Comment by madninja** [comment]
@benoitc We're doing some work to make connections and streams fully asynchronous since there's still too much state in a stack of connections and streams, which is causing some wedged swarms under load. 

As part of that re-factor I'll add some interop  by supporting mplex which seems to be the common denominator multiplexer.

**Comment by benoitc** [comment]
closing issue, i stil need somehow some documentation but will try to work around, with some mor specific question. Thanks for the answer anyway.
